name: First Workflow

on: workflow_dispatch

jobs:
  first-job: 
    runs-on: ubuntu-24.04
    steps:
      - name: print-greeting
        run: echo "I love Github Actions"
      - name: print-another
        run: echo "This is dope!"
